import image_importer from './helper_switchgen.js';

const OBJECT_TYPES = Object.freeze({
  STRUCTURE: 'Structure',
  RAW_MATERIAL: 'Raw Material',
  EQUIPMENT: 'Equipment',
});

const OBJECT_NAMES = Object.freeze({
  YMIR_FLESH: 'Ymir Flesh',
  WITHERED_BONE: 'Withered Bone',
});

const RAW_OBJECTS_DATA = [
  {
    name: 'Blood Pudding',
    notes: '',
    location: '',
    description: "It's bloody tasty.",
    ID: 'BloodPudding',
    type: 'Food',
    recipe: '2 Thistle 2 Bloodbag 4 Barley flour',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blueberries',
    notes: '',
    location: 'Found in bushes in the Black Forest',
    description: 'Tiny but tasty.',
    ID: 'Blueberries',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bread',
    notes: '',
    location: '',
    description: 'A tasty loaf of bread.',
    ID: 'Bread',
    type: 'Food',
    recipe: '10 Barley flour',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Carrot',
    notes: '',
    location: 'Plant Carrot Seeds',
    description: 'An orange treat.',
    ID: 'Carrot',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Carrot Soup',
    notes: '',
    location: '',
    description: 'A warm tasty soup made of mostly carrots.',
    ID: 'CarrotSoup',
    type: 'Food',
    recipe: '1 Mushroom 3 Carrots',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cloudberries',
    notes: '',
    location: 'Found in the Plains',
    description: 'The gold of the forest.',
    ID: 'Cloudberry',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cooked Fish',
    notes: '',
    location: 'Cook Raw fish',
    description: 'A tasty side of smoked fish.',
    ID: 'Fish Cooked',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cooked Lox Meat',
    notes: '',
    location: 'Cook Lox meat',
    description: 'A great hunk of tender meat, food fit for Valhalla!',
    ID: 'CookedLoxMeat',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cooked Meat',
    notes: '',
    location: 'Cook Raw meat',
    description: 'Roasted on the bone, fit for a feast.',
    ID: 'CookedMeat',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cooked Serpent Meat',
    notes: '',
    location: 'Cook Serpent meat',
    description: 'A cooked slice of sea serpent, smells good.',
    ID: 'SerpentMeatCooked',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fish Wraps',
    notes: '',
    location: '',
    description: 'Bread and fish, what more to wish?',
    ID: 'FishWraps',
    type: 'Food',
    recipe: '2 Cooked fish 4 Barley flour',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Grilled Neck Tail',
    notes: '',
    location: 'Cook Neck tail',
    description: 'This savoury, charcoal-grilled meat has a slight aroma of seaweed and grass.',
    ID: 'NeckTailGrilled',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Honey',
    notes: '',
    location: 'Found in Beehives',
    description: 'Sweet and tasty.',
    ID: 'Honey',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Lox Meat Pie',
    notes: '',
    location: '',
    description: 'Break the crust to release a cloud of fragrant steam. Delicious!',
    ID: 'LoxPie',
    type: 'Food',
    recipe: '4 Barley flour 2 Cloudberries 2 Cooked Lox meat',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Mushroom',
    notes: '',
    location: 'Found on the ground in the Meadows and Black Forest',
    description: 'Bounty of the forest.',
    ID: 'Mushroom',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Queens Jam',
    notes: '',
    location: '',
    description: 'That classic tasty blend of raspberries and blueberries.',
    ID: 'QueensJam',
    type: 'Food',
    recipe: '8 Raspberries 8 Blueberries',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Raspberries',
    notes: '',
    location: 'Found in bushes in the Meadows',
    description: 'Sweet and delicious.',
    ID: 'Raspberry',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Sausages',
    notes: '',
    location: '',
    description: 'Links of savory, smoked meat.',
    ID: 'Sausages',
    type: 'Food',
    recipe: '2 Entrails 1 Raw meat 4 Thistle',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Serpent Stew',
    notes: '',
    location: '',
    description: 'Smells of honey and serpent.',
    ID: 'SerpentStew',
    type: 'Food',
    recipe: '1 Mushroom 1 Cooked Serpent meat',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Turnip Stew',
    notes: '',
    location: '',
    description: 'Nutritious and restorative.',
    ID: 'TurnipStew',
    type: 'Food',
    recipe: '1 Raw meat 3 Turnips',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Yellow Mushroom',
    notes: '',
    location: 'Found in the Burial Chambers, Troll caves, and Sunken Crypts',
    description: 'An energetic glowing mushroom.',
    ID: 'MushroomYellow',
    type: 'Food',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Tasty Mead',
    notes: '',
    location: 'Ferment Mead base: Tasty (x10 Honey, x10 Raspberries, x5 Blueberries) for two days',
    description: 'The nectar of the gods, divine mead.',
    ID: 'MeadTasty',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Minor Healing Mead',
    notes: '',
    location: 'Ferment Mead base: Minor healing (x10 Honey, x5 Blueberries, x5 Raspberries, x1 Dandelion) for two days',
    description: 'Restores health.',
    ID: 'MeadHealthMinor',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Medium Healing Mead',
    notes: '',
    location: 'Ferment Mead base: Medium healing (x10 Honey, x4 Bloodbag, x10 Raspberries, x1 Dandelion) for two days',
    description: 'Restores health.',
    ID: 'MeadHealthMedium',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Minor Stamina Mead',
    notes: '',
    location: 'Ferment Mead base: Minor stamina (x10 Honey, x10 Raspberries, x10 Yellow mushroom) for two days',
    description: 'Restores stamina.',
    ID: 'MeadStaminaMinor',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Medium Stamina Mead',
    notes: '',
    location: 'Ferment Mead base: Medium stamina (x10 Honey, x10 Cloudberries, x10 Yellow mushroom) for two days',
    description: 'Restores stamina.',
    ID: 'MeadStaminaMedium',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Poison Resistance Mead',
    notes: '',
    location: 'Ferment Mead base: Poison resistance (x10 Honey, x5 Thistle, x1 Neck tail, x10 Coal) for two days',
    description: 'Fortifies you against poison.',
    ID: 'MeadPoisonResist',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Frost Resistance Mead',
    notes: '',
    location: 'Ferment Mead base: Frost resistance (x10 Honey, x5 Thistle, x2 Bloodbag, x1 Greydwarf eye) for two days',
    description: 'Protects against the cold.',
    ID: 'MeadFrostResist',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fire Resistance Barley Wine',
    notes: '',
    location: 'Ferment Barley wine base: Fire resistance (x10 Barley, x10 Cloudberries) for two days',
    description: 'Fortifies you against fire.',
    ID: 'BarleyWine',
    type: 'Alcohol',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Black Metal',
    notes: '',
    location: 'Smelt Black Metal scraps in a Blast Furnace',
    description: 'A heavy bar of dark metal.',
    ID: 'BlackMetal',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Black Metal Scrap',
    notes: '',
    location: 'Dropped by Fuling, Fuling Berserker, Fuling Shaman',
    description: 'A twisted hunk of dark metal.',
    ID: 'BlackMetalScrap',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze',
    notes: '',
    location: '',
    description: 'A strong alloy of copper and tin.',
    ID: 'Bronze',
    type: 'Ore',
    recipe: '2 Copper 1 Tin',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Nails',
    notes: '',
    location: '',
    description: 'Used in construction of ships and furniture.',
    ID: 'BronzeNails',
    type: 'Ore',
    recipe: '1 Bronze',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Copper',
    notes: '',
    location: 'Smelt Copper ore',
    description: 'A bar of pure copper ready to be worked.',
    ID: 'Copper',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Copper Ore',
    notes: '',
    location: 'Mined from Copper deposit',
    description: 'Unrefined copper. Needs to be refined in a smelter.',
    ID: 'CopperOre',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flametal',
    notes: '',
    location: 'Smelt Flametal ore in a Blast Furnace',
    description: 'The pure, shimmering core of a meteorite.',
    ID: 'Flametal',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flametal Ore',
    notes: '',
    location: 'Mined from Glowing Metal piles',
    description: 'Warm to the touch with glowing veins of strange metal. Needs to be refined in a smelter.',
    ID: 'FlametalOre',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron',
    notes: '',
    location: 'Smelted from Scrap Iron',
    description: 'A bar of pure iron ready to be worked.',
    ID: 'Iron',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Nails',
    notes: '',
    location: '',
    description: 'Needed for advanced construction projects.',
    ID: 'IronNails',
    type: 'Ore',
    recipe: '1 Iron',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Obsidian',
    notes: '',
    location: 'Mined in the Mountains',
    description: 'Dark volcanic glass.',
    ID: 'Obsidian',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Scrap Iron',
    notes: '',
    location: 'Mined from Muddy Scrap Piles Found in chests in the Sunken Crypts',
    description: "It's old and rusty but can be used and smelted again.",
    ID: 'IronScrap',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Silver',
    notes: '',
    location: 'Smelt Silver ore',
    description: 'A bar of pure silver ready to be worked.',
    ID: 'Silver',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Silver Ore',
    notes: '',
    location: 'Mined from silver deposits in the Mountains',
    description: 'Unrefined silver. Needs to be refined in a smelter.',
    ID: 'SilverOre',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Tin',
    notes: '',
    location: 'Smelt Tin ore',
    description: 'A bar of pure tin ready to be worked.',
    ID: 'Tin',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Tin Ore',
    notes: '',
    location: 'Mined from tin deposits near the rivers in the Black Forest',
    description: 'Unrefined tin. Needs to be refined in a smelter.',
    ID: 'TinOre',
    type: 'Ore',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ancient Bark',
    notes: '',
    location: 'Harvested from Ancient Trees in the Swamp',
    description: 'An ancient and sturdy material.',
    ID: 'ElderBark',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ancient Seed',
    notes: '',
    location: 'Dropped by Greydwarf Brute and Greydwarf Shaman Can be found randomly in chests',
    description: 'Held against your ear, you hear tiny whispering within...',
    ID: 'AncientSeed',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bone Fragments',
    notes: '',
    location: 'Dropped by Skeletons Found in the Burial Chambers and Black Forest',
    description: 'A pile of shattered bones.',
    ID: 'BoneFragments',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Chain',
    notes: '',
    location: 'Dropped by Wraiths Found in Sunken Crypts',
    description: 'A link of iron chain.',
    ID: 'Chain',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Chitin',
    notes: '',
    location: 'Acquired by mining Abyssal Barnacles in the Ocean',
    description: 'A shard of crustacean shell.',
    ID: 'Chitin',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Coal',
    notes: '',
    location: 'Created by overcooking meat Crafted in a charcoal kiln using wood Dropped by Surtlings',
    description: 'A lump of coal.',
    ID: 'Coal',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Crystal',
    notes: '',
    location: 'Dropped by Stone Golems in the Mountains',
    description: 'A shard of crystal from deep within the earth.',
    ID: 'Crystal',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Deer Hide',
    notes: '',
    location: 'Dropped by Deer Found in chests',
    description: 'A cleaned hide from a deer.',
    ID: 'DeerHide',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Dragon Tear',
    notes: '',
    location: 'Dropped by Modor',
    description: 'The last frozen tears of a dragon, pulsating with mysterious energy.',
    ID: 'DragonTear',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Entrails',
    notes: '',
    location: 'Dropped by Draugr',
    description: "A slimy length of something's insides.",
    ID: 'Entrails',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Feathers',
    notes: '',
    location: 'Dropped by Seagulls Found in chests in the Meadows and Black Forest Rare drop from chopping down trees',
    description: 'A small pile of feathers.',
    ID: 'Feathers',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flint',
    notes: '',
    location: 'Found along the river and shoreline in the Meadows',
    description: 'Can be shaped into sharp blades.',
    ID: 'Flint',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Freeze Gland',
    notes: '',
    location: 'Dropped by Drakes',
    description: 'This mysterious organ keeps a perfect temperature.',
    ID: 'FreezeGland',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fuling Totem',
    notes: '',
    location: 'Found in Fuling Villages Dropped by Fuling Berserker',
    description: 'Channels the ancient power of Yagluth.',
    ID: 'N/A',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Greydwarf Eye',
    notes: '',
    location: 'Dropped by Greyling, Greydwarf, Greydwarf Brute, and Greydwarf Shaman.',
    description: 'Milky eyeball of a Greydwarf.',
    ID: 'GreydwarfEye',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Guck',
    notes: '',
    location: 'Found in Gucksacks in the Swamp',
    description: 'It smells like fermented fish.',
    ID: 'Guck',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Hard Antler',
    notes: '',
    location: 'Dropped by Eikthyr',
    description: 'A piece of very hard antler.',
    ID: 'HardAntler',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Leather Scraps',
    notes: '',
    location: 'Dropped by Boar Found in muddy scrap piles Found in chests in the Meadows',
    description: 'A small pile of leather scraps.',
    ID: 'LeatherScraps',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Linen Thread',
    notes: '',
    location: '',
    description: 'A fine linen thread made out of a strong flax filament.',
    ID: 'LinenThread',
    type: 'Misc',
    recipe: '1 Flax',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Lox Pelt',
    notes: '',
    location: 'Dropped by Lox',
    description: 'A heavy pelt of thick, musty fur.',
    ID: 'LoxPelt',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Needle',
    notes: '',
    location: 'Dropped by Deathsquito',
    description: 'The pointy end of a Deathsquito.',
    ID: 'Needle',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ooze',
    notes: '',
    location: 'Dropped by Blob and Oozer',
    description: 'Rotten and putrid-smelling. Why do you want this?',
    ID: 'Ooze',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Resin',
    notes: '',
    location: 'Dropped by Greydwarfs',
    description: 'Sticky tree resin that insulates well. If put to the flame it burns slow and steady.',
    ID: 'Resin',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Serpent Scale',
    notes: '',
    location: 'Dropped by Serpents',
    description: 'The shiny metal-like scale from a sea serpent.',
    ID: 'SerpentScale',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Stone',
    notes: '',
    location: 'Found all over the ground Mined from rocks',
    description: "It's a rock.",
    ID: 'Stone',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Surtling Core',
    notes: '',
    location: 'Dropped by Surtlings Found in Burial Chambers',
    description: 'It throbs with inner heat.',
    ID: 'SurtlingCore',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Thistle',
    notes: '',
    location: 'Found in the Black Forest and Swamp',
    description: 'Beatiful but prickly.',
    ID: 'Thistle',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Troll Hide',
    notes: '',
    location: 'Dropped by Trolls Found in chests in Black Forest',
    description: 'A thick and sturdy hide. This is why trolls are so hard to kill.',
    ID: 'TrollHide',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wolf Fang',
    notes: '',
    location: 'Dropped by Wolves',
    description: 'Still sharp.',
    ID: 'WolfFang',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wolf Pelt',
    notes: '',
    location: 'Dropped by Wolves',
    description: 'A pelt of shaggy fur.',
    ID: 'WolfPelt',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Withered Bone',
    notes: '',
    location: 'Found in muddy scrap piles Found in Sunken Crypts',
    description: 'A giant bone, knotted like old wood.',
    ID: 'WitheredBone',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ymir Flesh',
    notes: '',
    location: 'Purchased from Haldor for 120 coins',
    description: 'The earthy remains of the giant Ymir.',
    ID: 'YmirRemains',
    type: 'Misc',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wood Arrow',
    notes: '',
    location: '',
    description: 'An arrow of sharpened wood.',
    ID: 'ArrowWood',
    type: 'Arrow',
    recipe: '8 Wood',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flinthead Arrow',
    notes: '',
    location: '',
    description: 'A hide-breaker with a head of flint.',
    ID: 'ArrowFlint',
    type: 'Arrow',
    recipe: '8 Wood 2 Flint 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronzehead Arrow',
    notes: '',
    location: '',
    description: 'Sharper than flint, a sleek messenger of death.',
    ID: 'ArrowBronze',
    type: 'Arrow',
    recipe: '8 Wood 1 Bronze 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ironhead Arrow',
    notes: '',
    location: '',
    description: 'Capped with iron and flighted with dark feathers.',
    ID: 'ArrowIron',
    type: 'Arrow',
    recipe: '8 Wood 1 Iron 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Obsidian Arrow',
    notes: '',
    location: '',
    description: 'A sliver of darkness.',
    ID: 'ArrowObsidian',
    type: 'Arrow',
    recipe: '8 Wood 4 Obsidian 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Needle Arrow',
    notes: '',
    location: '',
    description: 'The final stitch.',
    ID: 'ArrowNeedle',
    type: 'Arrow',
    recipe: '4 Needle 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fire Arrow',
    notes: '',
    location: '',
    description: 'This arrow burns whatever it pierces.',
    ID: 'ArrowFire',
    type: 'Arrow',
    recipe: '8 Wood 8 Resin 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Frost Arrow',
    notes: '',
    location: '',
    description: 'A shard of piercing ice.',
    ID: 'ArrowFrost',
    type: 'Arrow',
    recipe: '8 Wood 4 Obsidian 2 Feathers 1 Freeze Gland',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Poison Arrow',
    notes: '',
    location: '',
    description: 'A bitter sting from afar.',
    ID: 'ArrowPoison',
    type: 'Arrow',
    recipe: '8 Wood 4 Obsidian 2 Feathers 2 Ooze',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Silver Arrow',
    notes: '',
    location: '',
    description: 'A needle to calm restless spirits.',
    ID: 'ArrowSilver',
    type: 'Arrow',
    recipe: '8 Wood 1 Silver 2 Feathers',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Sharpening Stone',
    notes: '',
    location: '',
    description: 'A whetstone wheel ready to spin.',
    ID: 'SharpeningStone',
    type: 'Misc',
    recipe: '5 Stone',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Workbench',
    notes: 'Used for crafting and building',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '10 Wood',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Chopping Block',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '10 Wood 10 Flint',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Tanning Rack',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Adze',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Tool Shelf',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Forge',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Forge Cooler',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Anvils',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Forge Toolrack',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: "Smith's Anvil",
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Forge Bellows',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Grinding Wheel',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Charcoal Kiln',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Smelter',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blast Furnace',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cauldron',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fermenter',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Stonecutter',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Artisan Table',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Windmill',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Spinning Wheel',
    notes: '',
    location: '',
    description: '',
    ID: '',
    type: 'Structure',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Stone Axe',
    notes: '',
    location: '5 Wood 4 Stone',
    description: 'A crude axe for tree-felling',
    ID: 'AxeStone',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flint Axe',
    notes: '',
    location: '4 Wood 6  Flint',
    description: 'Sharper than stone.',
    ID: 'AxeFlint',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Axe',
    notes: '',
    location: '4 Wood 8 Bronze 2 Leather scraps',
    description: 'A bright and burnished blade, curved like a smile.',
    ID: 'AxeBronze',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Axe',
    notes: '',
    location: '4 Wood 20 Iron 2 Leather scraps',
    description: "Sharp and strong, a woodcutter's friend.",
    ID: 'AxeIron',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blackmetal Axe',
    notes: '',
    location: '6 Fine wood 20 Black metal 5 Linen thread',
    description: 'A perfectly-balanced axe forged from dark metal with an emerald sheen.',
    ID: 'AxeBlackMetal',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Antler Pickaxe',
    notes: '',
    location: '10 Wood 1 Hard antler',
    description: 'This tool is hard enough to crack even the most stubborn rocks.',
    ID: 'PickaxeAntler',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Pickaxe',
    notes: '',
    location: '3 Core wood 10 Bronze',
    description: 'A good bronze pick. Can break very hard rocks.',
    ID: 'PickaxeBronze',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Pickaxe',
    notes: '',
    location: '3 Core wood 20 Iron',
    description: 'A sturdy tool of hardened iron.',
    ID: 'PickaxeIron',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Hammer',
    notes: '',
    location: '3 Wood 2 Stone',
    description: 'With this to your hand, you can raise high halls and mighty fortifications.',
    ID: 'Hammer',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Hoe',
    notes: '',
    location: '5 Wood 2 Stone',
    description: "A farmer's tool for working the earth.",
    ID: 'Hoe',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cultivator',
    notes: '',
    location: '5 Core wood 5 Bronze',
    description: 'A farming tool for tilling soil.',
    ID: 'Cultivator',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fishing Rod',
    notes: '',
    location: 'Not craftable. Must purchase from Haldor for 350 coins.',
    description: 'Stand issue dvergr fishing rod .',
    ID: 'FishingRod',
    type: 'Tool',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Torch',
    notes: '',
    location: '',
    description: 'It brings light and warmth, drives back the darkness.',
    ID: 'Torch',
    type: 'Tool',
    recipe: '1 Wood 1 Resin',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Rag Tunic',
    notes: '',
    location: '',
    description: 'Better than nothing.',
    ID: 'ArmorRagsChest',
    type: 'Armor',
    recipe: '5 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Rag Pants',
    notes: '',
    location: '',
    description: 'A simple remedy for nudity.',
    ID: 'ArmorRagsLegs',
    type: 'Armor',
    recipe: '5 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Leather Helmet',
    notes: '',
    location: '',
    description: 'A hood of toughened leather.',
    ID: 'HelmetLeather',
    type: 'Armor',
    recipe: '6 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Leather Tunic',
    notes: '',
    location: '',
    description: 'A tunic made from animal hide.',
    ID: 'ArmorLeatherChest',
    type: 'Armor',
    recipe: '6 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Leather Pants',
    notes: '',
    location: '',
    description: 'They squeak a little when you walk.',
    ID: 'ArmorLeatherLegs',
    type: 'Armor',
    recipe: '6 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Deer Hide Cape',
    notes: '',
    location: '',
    description: 'Rustic chic.',
    ID: 'CapeDeerHide',
    type: 'Armor',
    recipe: '4 Deer hide 5 Bone fragments',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Troll Leather Helmet',
    notes: '',
    location: '',
    description: 'Trollskin is hard to work but makes exceptional armor.',
    ID: 'HelmetTrollLeather',
    type: 'Armor',
    recipe: '5 Troll hide 3 Bone fragments',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Troll Leather Tunic',
    notes: '',
    location: '',
    description: 'Trolls are hard to skin but their leather is tough and warm.',
    ID: 'ArmorTrollLeatherChest',
    type: 'Armor',
    recipe: '5 Troll hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Troll Leather Pants',
    notes: '',
    location: '',
    description: 'Leggings of tough troll hide.',
    ID: 'ArmorTrollLeatherLegs',
    type: 'Armor',
    recipe: '5 Troll hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Troll Hide Cape',
    notes: '',
    location: '',
    description: 'Trollskin is tough and supple.',
    ID: 'CapeTrollHide',
    type: 'Armor',
    recipe: '10 Troll hide 10 Bone fragments',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Helmet',
    notes: '',
    location: '',
    description: 'This will help to keep your brains inside your skull.',
    ID: 'HelmetBronze',
    type: 'Armor',
    recipe: '5 Bronze 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Plate Cuirass',
    notes: '',
    location: '',
    description: 'A breastplate of hammered bronze.',
    ID: 'ArmorBronzeChest',
    type: 'Armor',
    recipe: '5 Bronze 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Plate Leggings',
    notes: '',
    location: '',
    description: 'Bronze greaves to sheild your legs.',
    ID: 'ArmorBronzeLegs',
    type: 'Armor',
    recipe: '5 Bronze 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Helmet',
    notes: '',
    location: '',
    description: 'A helm of polished iron, fit for a hero.',
    ID: 'HelmetIron',
    type: 'Armor',
    recipe: '20 Iron 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Scale Mail',
    notes: '',
    location: '',
    description: 'An iron scale mail , this will turn all but the strongest of blows.',
    ID: 'ArmorIronChest',
    type: 'Armor',
    recipe: '20 Iron 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Greaves',
    notes: '',
    location: '',
    description: 'Iron greaves to protect your legs.',
    ID: 'ArmorIronLegs',
    type: 'Armor',
    recipe: '20 Iron 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Drake Helmet',
    notes: '',
    location: '',
    description: 'An elaborate and finely-crafted helm.',
    ID: 'HelmetDrake',
    type: 'Armor',
    recipe: '20 Silver 2 Wolf pelt 2 Drake trophy',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wolf Armor Chest',
    notes: '',
    location: '',
    description: 'A wolfskin jerkin, warm and wild-looking. It protects against the cold.',
    ID: 'ArmorWolfChest',
    type: 'Armor',
    recipe: '20 Silver 5 Wolf pelt 1 Chain',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wolf Armor Legs',
    notes: '',
    location: '',
    description: 'Shaggy breeches of wolfskin.',
    ID: 'ArmorWolfLegs',
    type: 'Armor',
    recipe: '20 Silver 5 Wolf pelt 4 Wolf fang',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wolf Fur Cape',
    notes: '',
    location: '',
    description: 'Wolves are natural survivors. This one was just unlucky. Now its pelt will warm you in the snow.',
    ID: 'CapeWolf',
    type: 'Armor',
    recipe: '6 Wolf pelt 4 Silver 1 Wolf trophy',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Padded Helmet',
    notes: '',
    location: '',
    description: 'A snug fit, finely made.',
    ID: 'HelmetPadded',
    type: 'Armor',
    recipe: '10 Iron 15 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Padded Cuirass',
    notes: '',
    location: '',
    description: 'Finely wrought and strong enough to turn even the sharpest blades.',
    ID: 'ArmorPaddedCuirass',
    type: 'Armor',
    recipe: '10 Iron 20 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Padded Greaves',
    notes: '',
    location: '',
    description: 'Expertly crafted leg protection.',
    ID: 'ArmorPaddedGreaves',
    type: 'Armor',
    recipe: '10 Iron 20 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Linen Cape',
    notes: '',
    location: '',
    description: "A simple traveler's cape.",
    ID: 'CapeLinen',
    type: 'Armor',
    recipe: '20 Linen thread 1 Silver',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Lox Cape',
    notes: '',
    location: '',
    description: 'A pelt from one of the great beasts, thick and warm.',
    ID: 'CapeLox',
    type: 'Armor',
    recipe: '6 Lox pelt 2 Silver',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Cape of Odin',
    notes: '',
    location: '',
    description: "Odin's finest warriors deserve the finest cloth.",
    ID: 'CapeOdin',
    type: 'Armor',
    recipe: '10 Leather scraps 4 Coal',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Hood of Odin',
    notes: '',
    location: '',
    description: "Odin's finest warriors deserve the finest cloth.",
    ID: 'HelmetOdin',
    type: 'Armor',
    recipe: '10 Leather scraps 4 Coal',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Dverger Circlet',
    notes: '',
    location: 'Not craftable. Must purchase from Haldor for 620 coins.',
    description: 'A portable perpetual light source for the dungeon explorer.',
    ID: 'HelmetDverger',
    type: 'Armor',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Yule Hat',
    notes: '',
    location: 'Not craftable. Must purchase from Haldor for 100 coins.',
    description: 'A red hat in the style of house gnomes.',
    ID: 'HelmetYule',
    type: 'Armor',
    recipe: '',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Club',
    notes: '',
    location: '',
    description: 'A crude but useful weapon.',
    ID: 'Club',
    type: 'Weapon',
    recipe: '6 Wood',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Mace',
    notes: '',
    location: '',
    description: 'A headache on a stick.',
    ID: 'MaceBronze',
    type: 'Weapon',
    recipe: '4 Wood 8 Bronze 3 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Mace',
    notes: '',
    location: '',
    description: 'A fist-sized lump of iron on a wooden shaft.',
    ID: 'MaceIron',
    type: 'Weapon',
    recipe: '4 Wood 20 Iron 3 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Porcupine',
    notes: '',
    location: '',
    description: 'A deadly weapon, bristling with fiendish spikes.',
    ID: 'MaceNeedle',
    type: 'Weapon',
    recipe: '5 Fine wood 20 Iron 5 Needle 10 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Frostner',
    notes: '',
    location: '',
    description: 'The dead fear silver. Remind them why.',
    ID: 'MaceSilver',
    type: 'Weapon',
    recipe: '10 Ancient bark 30 Silver 5 Ymir flesh 5 Freeze gland',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Stagbreaker',
    notes: '',
    location: '',
    description: "A weapon worthy of the gods! If you get hit with this, you'll know it...",
    ID: 'SledgeStagbreaker',
    type: 'Weapon',
    recipe: '20 Core wood 5 Deer trophy 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Sledge',
    notes: '',
    location: '',
    description: 'A mighty hammer , worthy of a champion.',
    ID: 'SledgeIron',
    type: 'Weapon',
    recipe: '10 Ancient bark 30 Iron 4 Ymir flesh 1 Draugr Elite trophy',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Battleaxe',
    notes: '',
    location: '',
    description: "Skull-splitter, a warrior's joy.",
    ID: 'Battleaxe',
    type: 'Weapon',
    recipe: '30 Ancient bark 35 Iron 4 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flint Knife',
    notes: '',
    location: '',
    description: 'Sharpened flint, a reliable tool.',
    ID: 'KnifeFlint',
    type: 'Weapon',
    recipe: '2 Wood 4 Flint 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Copper Knife',
    notes: '',
    location: '',
    description: 'A glittering copper knife .',
    ID: 'KnifeCopper',
    type: 'Weapon',
    recipe: '3 Wood 8 Copper',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Abyssal Razor',
    notes: '',
    location: '',
    description: 'A knife from the deep.',
    ID: 'KnifeChitin',
    type: 'Weapon',
    recipe: '4 Fine wood 20 Chitin 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blackmetal Knife',
    notes: '',
    location: '',
    description: 'A darkling blade, strong and sharp.',
    ID: 'KnifeBlackMetal',
    type: 'Weapon',
    recipe: '4 Fine wood 20 Black metal 5 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Sword',
    notes: '',
    location: '',
    description: 'Blood-drinker, a thirsty friend.',
    ID: 'SwordBronze',
    type: 'Weapon',
    recipe: '2 Wood 8 Bronze 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Sword',
    notes: '',
    location: '',
    description: 'The straight line between life and death runs along the edge of this blade.',
    ID: 'SwordIron',
    type: 'Weapon',
    recipe: '2 Wood 20 Iron 3 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Silver Sword',
    notes: '',
    location: '',
    description: 'Purest of metals, nothing unclean can abide its touch.',
    ID: 'SwordSilver',
    type: 'Weapon',
    recipe: '2 Wood 40 Silver 3 Leather scraps 5 Iron',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blackmetal Sword',
    notes: '',
    location: '',
    description: 'A thing of death and beauty, it catches the light with a greenish glow.',
    ID: 'SwordBlackmetal',
    type: 'Weapon',
    recipe: '2 Fine wood 20 Black metal 5 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Atgeir',
    notes: '',
    location: '',
    description: "A true warrior's tool.",
    ID: 'AtgeirBronze',
    type: 'Weapon',
    recipe: '10 Wood 8 Bronze 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Atgeir',
    notes: '',
    location: '',
    description: 'Blood-drinker, skull-cracker, death-bringer.',
    ID: 'AtgeirIron',
    type: 'Weapon',
    recipe: '10 Wood 30 Iron 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Blackmetal Atgeir',
    notes: '',
    location: '',
    description: 'A vicious hewing-axe of almost unbreakable black metal.',
    ID: 'AtgeirBlackmetal',
    type: 'Weapon',
    recipe: '10 Fine wood 30 Black metal 5 Linen thread',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Flint Spear',
    notes: '',
    location: '',
    description: 'If your eye marks a thing for death, let your arm send the messenger.',
    ID: 'SpearFlint',
    type: 'Weapon',
    recipe: '5 Wood 10 Flint 2 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Spear',
    notes: '',
    location: '',
    description: 'A sturdy spear with a head of burnished bronze.',
    ID: 'SpearBronze',
    type: 'Weapon',
    recipe: '5 Wood 6 Bronze 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Ancient Bark Spear',
    notes: '',
    location: '',
    description: 'Despite its gnarled look, this spear is strong and perfectly balanced.',
    ID: 'SpearElderbark',
    type: 'Weapon',
    recipe: '4 Troll hide 10 Iron 10 Ancient bark',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Fang Spear',
    notes: '',
    location: '',
    description: "Even in death, the wolf's tooth aches for flesh.",
    ID: 'SpearWolfFang',
    type: 'Weapon',
    recipe: '10 Ancient bark 4 Wolf fang 2 Leather scraps 2 Silver',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Abyssal Harpoon',
    notes: '',
    location: '',
    description: "The ocean's wrath.",
    ID: 'SpearChitin',
    type: 'Weapon',
    recipe: '8 Fine wood 30 Chitin 3 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Crude Bow',
    notes: '',
    location: '',
    description: 'A crude but functional bow.',
    ID: 'Bow',
    type: 'Weapon',
    recipe: '10 Wood 8 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Finewood Bow',
    notes: '',
    location: '',
    description: 'A simple bow of strong and supple wood.',
    ID: 'BowFineWood',
    type: 'Weapon',
    recipe: '10 Fine wood 10 Core wood 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Huntsman Bow',
    notes: '',
    location: '',
    description: "Finely worked and strung, a huntsman's joy.",
    ID: 'BowHuntsman',
    type: 'Weapon',
    recipe: '10 Fine wood 20 Iron 10 Feathers 2 Deer hide',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Draugr Fang',
    notes: '',
    location: '',
    description: 'Dark wood strung with glistening sinew, a vicious thing.',
    ID: 'BowDraugrFang',
    type: 'Weapon',
    recipe: '10 Ancient bark 20 Silver 2 Deer hide 10 guck',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wood Shield',
    notes: '',
    location: '',
    description: 'A simple wooden shield.',
    ID: 'ShieldWood',
    type: 'Weapon',
    recipe: '10 Wood 4 Resin 4 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Bronze Buckler',
    notes: '',
    location: '',
    description: 'A shield of burnished bronze, good to turn a blade or two.',
    ID: 'ShieldBronzeBuckler',
    type: 'Weapon',
    recipe: '10 Bronze 4 Wood',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Banded Shield',
    notes: '',
    location: '',
    description: "Banded with hoops of iron, a true warrior's companion.",
    ID: 'ShieldBanded',
    type: 'Weapon',
    recipe: '10 Fine wood 8 Iron',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Silver Shield',
    notes: '',
    location: '',
    description: 'A shield of radiant silver.',
    ID: 'ShieldSilver',
    type: 'Weapon',
    recipe: '10 Fine wood 8 Silver',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Black Metal Shield',
    notes: '',
    location: '',
    description: 'Fashioned from the strongest metal, able to turn even the deadliest blades.',
    ID: 'ShieldBlackmetal',
    type: 'Weapon',
    recipe: '10 Fine wood 8 Black metal 5 Chain',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Wood Tower Shield',
    notes: '',
    location: '',
    description: 'A rough but heavy wooden shield.',
    ID: 'ShieldWoodTower',
    type: 'Weapon',
    recipe: '10 Wood 6 Leather scraps',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Iron Tower Shield',
    notes: '',
    location: '',
    description: 'A tall shield of strong iron.',
    ID: 'ShieldIronTower',
    type: 'Weapon',
    recipe: '15 Fine wood 10 Iron',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Black Metal Tower Shield',
    notes: '',
    location: '',
    description: 'A tower shield of gleaming dark metal.',
    ID: 'ShieldBlackmetalTower',
    type: 'Weapon',
    recipe: '15 Fine wood 10 Black metal 7 Chain',
    prerequisites: '',
    subtype: '',
  },
  {
    name: 'Serpent Scale Shield',
    notes: '',
    location: '',
    description: 'A sturdy shield of overlapping scales.',
    ID: 'ShieldSerpentscale',
    type: 'Weapon',
    recipe: '10 Fine wood 4 Iron 8 Serpent scale',
    prerequisites: '',
    subtype: '',
  },
];

const ALL_OBJECTS_DATA = {};
RAW_OBJECTS_DATA.forEach((rawData) => {
  ALL_OBJECTS_DATA[rawData.name] = rawData;
  ALL_OBJECTS_DATA[rawData.name].image = image_importer(rawData.name);
});

export {
  OBJECT_NAMES, ALL_OBJECTS_DATA,
};
